export type ProductEditorSheetProps = {
    open: boolean;
    reference: string;
    title: string;
    saveLabel: string;
    deleteLabel: string;
    nameLabel: string;
    priceLabel: string;
    stockLabel: string;
    maintenanceLabel: string;
    descriptionLabel: string;
    imageLabel: string;
    imageActionLabel: string;
    imageLoadingLabel: string;
    imageEmptyLabel: string;
    name: string;
    price: number;
    stock: number;
    stockDisabled?: boolean;
    isService?: boolean;
    maintenance: boolean;
    description: string;
    imagePreview: string | null;
    imageLoading: boolean;
    imageUpdating: boolean;
    saving: boolean;
    deleting: boolean;
    onOpenChange: (open: boolean) => void;
    onNameChange: (value: string) => void;
    onPriceChange: (value: number) => void;
    onStockChange: (value: number) => void;
    onMaintenanceChange: (value: boolean) => void;
    onDescriptionChange: (value: string) => void;
    onImageFileChange: (file: File) => Promise<void> | void;
    onSave: () => void;
    onDelete: () => void;
};
